[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"
  PUBLIC_SUPABASE_URL = "https://pmmkfrohclzpwpnbtajc.supabase.co"
  PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtbWtmcm9oY2x6cHdwbmJ0YWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA4MTM4MDYsImV4cCI6MjA0NjM4OTgwNn0.2m8L21ploy11YBpO3Wf0Qv7uZ243oIqA2PP9DuaR0As"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200